# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "/usr/local/go/bin/go build -o ./tmp/app ./cmd/api"
bin = "./tmp/app"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp", "vendor", ".git", "node_modules"]
poll = true
poll_interval = 1000   

[log]
time = true