services:
  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'db.runCommand({ ping: 1 })' | mongosh --quiet mongodb://localhost:27017/test || exit 1",
        ]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build: .
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DB_NAME=appdb
      - PORT=8080
    ports: ["8080:8080"]
    volumes:
      - .:/app

volumes:
  mongo_data:
