# Create Item
POST http://localhost:8080/items
Content-Type: application/json

{
  "name": "first"
}

###

# List Items
GET http://localhost:8080/items

###


# Get Item by ID
GET http://localhost:8080/items/689376daa0487c91d6071584
Content-Type: application/json